### ISSUE TITLE
Add support for outputting results to a file

### ISSUE THREAD

**Issue by kehoecj** [Boeing/config-file-validator#101]
## Description
We support JSON and (coming-soon) Junit and SARIF formats. These reporter formats are generally more useful saved as file output rather than stdout. Currently users would be required to redirect the stdout of these formats to a file themselves but it'd be much easier if the config-file-validation supported that as a built-in feature

**Comment by iyoshiha** [comment]
@kehoecj 
Hi, I'm interested in take on this issue. Please let me clarify the specifications.

- Manage the output of results to a file when the "output-dest" flag is provided with the value "the path to a directory or a file."
- Currently, config-file-validator only supports JSON and the standard format. When the reporter flag with the JSON format is provided, output the results to a file. For the standard (default) format and when the -output-dest flag is provided, simply ignore it.
- Create a new file named "result.json" at the current working directory when the -output-dest flag with no value or empty string is provided.
- Overwrite the file when an existing file is specified as the value of the output-dest flag.
- Create a new file named "result.json" when an existing directory is specified as the value of the output-dest flag.
- Create a new file named after the value of the output-dest flag when a non-existing file is specified as its value.
- Return an error when a non-existing directory is specified as the value of the output-dest flag.

Do the above specifications meet your requirements? Your feedback is valuable. Thank you for your attention.
