### ISSUE TITLE
output nothing to stdout 

### ISSUE THREAD

**Issue by iyoshiha** [Boeing/config-file-validator#105]
if this [PR](https://github.com/Boeing/config-file-validator/pull/104) is merged, i want `--quiet` option which outputs nothing to stdout.

**Comment by MaxV148** [comment]
I would like to contribute. Just to be sure the —quiet flag should also suppress the message if the validation failed ? @iyoshiha

**Comment by kehoecj** [comment]
@MaxV148 @iyoshiha #101 was closed so this can be worked

**Comment by iyoshiha** [comment]
@MaxV148 
i think the failed results shouldn't be output too but if some error occured it should be output.

**Comment by iyoshiha** [comment]
> @MaxV148 and @iyoshiha Do you agree?

Yes, it's perfect.
