### ISSUE TITLE
Add support for setting CLI arguments using environment variables

### ISSUE THREAD

**Issue by kehoecj** [Boeing/config-file-validator#111]
Enable users to set all optional CLI arguments as environment variables instead of (or in additional to) directly passing them as CLI arguments. For example running `export CFV_REPORTER="json` would produce JSON output. If both a CLI argument and environment variable are provided the CLI argument should win over the environment var or any type of merging of the options.

**Comment by nikonhub** [comment]
Hello. Could I work on this one ?

**Comment by kehoecj** [comment]
@nikonhub assigned it to you!
