### ISSUE TITLE
Add gocyclo check to pipeline

### ISSUE THREAD

**Issue by kehoecj** [Boeing/config-file-validator#120]
Add a stage in the pipeline to run through each check in the [Go Report Card](https://goreportcard.com/report/github.com/Boeing/config-file-validator)

**Comment by kehoecj** [comment]
Thanks for the PR @Bhargav-InfraCloud !

**Comment by ccoVeille** [comment]
For records, I opened https://github.com/gojp/goreportcard/issues/425 because goreportcard seems to be very outdated

**Comment by Bhargav-InfraCloud** [comment]
Thanks! @kehoecj 😊
