### ISSUE TITLE
Release 1.6.0

### ISSUE THREAD

**Issue by kehoecj** [Boeing/config-file-validator#126]
Prepare the v1.6.0 release

There have been many changes since v1.5.0 that need to be documented in the README:

* Junit Support (add value in reporters list)
* HOCON file type
* ENV file type support
* Support mixed and upper case file extensions (i.e. `.TOML` and `.Toml`)
* Added groupby functionality for JSON and Stdout reporters
* Added the ability to produce a file from the reporter
* Optimized element lookup in the fsfinder to improve performance by 30-50%
* Support for the `--quiet` flag
* Update the archlinux PKGBUILD

**Comment by HakanVardarr** [comment]
You can add quiet flag also.

**Comment by kehoecj** [comment]
> You can add quiet flag also.

Thanks! Added
