### ISSUE TITLE
Add command line argument to ignore file types

### ISSUE THREAD

**Issue by kehoecj** [Boeing/config-file-validator#13]
## Description

The current implementation of the config-file-validator will scan and report on all supported file types that it discovers in the search path. This may not be desired behavior for some teams that just want to target a subset of the supported configuration file types. We should add a CLI argument to allow users to specify a list of supported file types to exclude from the validation run. 

## Potential Solution
```
validator --search-path=/path/to/search --exclude-file-types=yaml,json
```

**Comment by ravsii** [comment]
Hi. I would like to try to implement this one. Seems like an easy first issue.
I'm new to the project, is there anything I should know beforehand?

**Comment by kehoecj** [comment]
Hi @ravsii - thanks for being willing to contribute! You should be able to clone and run on any Go 1.18+ environment (Windows/Linux/MacOs). One thing to note is that we are trying to keep the same functionality for including the CLI functionality as a library in go as well as running as a CLI tool. Reach out if you run into any issues or have any questions

**Comment by ravsii** [comment]
Sure, thanks @kehoecj !
You can assign me to the issue and I'm gonna submit a PR as soon I finish

**Comment by kehoecj** [comment]
@ravsii Thank you for the contribution!
