### ISSUE TITLE
Fix Go Report Card Issues

### ISSUE THREAD

**Issue by kehoecj** [Boeing/config-file-validator#130]
Fix all issues identified in our latest [Go Report Card](https://goreportcard.com/report/github.com/Boeing/config-file-validator) for v1.6.0

**Comment by ashish111333** [comment]
I would like to work on this,Pls assign it to me.

**Comment by ccoVeille** [comment]
@HakanVardarr started to implement it in #131

**Comment by ccoVeille** [comment]
@kehoecj could you assign the issue to @HakanVardarr ?

Also, is there any other issue that @ashish111333 could look at?

**Comment by ccoVeille** [comment]
GitHub…

OK, thanks

**Comment by HakanVardarr** [comment]
> > @kehoecj could you assign the issue to @HakanVardarr ?
> > Also, is there any other issue that @ashish111333 could look at?
> 
> I tired but it doesn't seem like I can until @HakanVardarr makes a comment on the issue

😀

**Comment by ccoVeille** [comment]
I think the issue is now closed as #131 was merged
