### ISSUE TITLE
Add option to turn off or limit the depth of recursive scanning

### ISSUE THREAD

**Issue by kehoecj** [Boeing/config-file-validator#14]
## Description
The config-file-validator will recursively scan the provided search path until it reaches the end of the directory structure. This may not be the desired behavior for some teams. We should offer an option to limit the depth of recursion as well as disable it entirely.

## Potential implementation

Disable recursion
```
validator --depth=0 path/to/search
```

Limit the depth of recursion
```
validator --depth=1 path/to/search
```

**Comment by sandyydk** [comment]
@kehoecj I can pick this up? Thanks in advance.

**Comment by kehoecj** [comment]
> @kehoecj I can pick this up? Thanks in advance.

I've got you assigned to #36 and #47 so I'll leave this open for others for now. If you finish those up and no one else has claimed this one then you can definitely work it

**Comment by kehoecj** [comment]
> > @kehoecj I can pick this up? Thanks in advance.
> 
> I've got you assigned to #36 and #47 so I'll leave this open for others for now. If you finish those up and no one else has claimed this one then you can definitely work it

Although if you want to swap this one for #47 that's fine too - just let me know. I just don't want someone loaded with more than 2 stories in progress at a time.

**Comment by sandyydk** [comment]
@kehoecj https://github.com/Boeing/config-file-validator/pull/54
