### ISSUE TITLE
Dockerfile linter

### ISSUE THREAD

**Issue by ccoVeille** [Boeing/config-file-validator#144]
Dockerfile is a pretty common configuration format.

They are many linters, I found this one in Go

https://github.com/zabio3/godolint

There are others of course.

So maybe, you could validate dockerfile

**Comment by kehoecj** [comment]
I think most projects already use hadolint which would be more robust than what we could provide. I think it's also slightly out of scope of the tool as we're focused on config files that can ultimately be tied to a schema.

**Comment by ccoVeille** [comment]
That's right.
