### ISSUE TITLE
Add List of file types that can be excluded in the `--help` output

### ISSUE THREAD

**Issue by kehoecj** [Boeing/config-file-validator#170]
When running `validator --help` the `--exclude-type` flag doesn't provide a list to the users of the types that can be excluded. Add the list to the output by looking through the type names in [this file](https://github.com/Boeing/config-file-validator/blob/main/pkg/filetype/file_type.go)

**Comment by timwehrle** [comment]
@kehoecj This still open? If yes, I can look into it.

**Comment by danielingegneri** [comment]
@timwehrle I just created a pull request, what timing!
