### ISSUE TITLE
Update example execution images in the README

### ISSUE THREAD

**Issue by kehoecj** [Boeing/config-file-validator#175]
We currently use images to show example validator runs. These don't look great and since they are from the maintainer's desktop it makes it difficult for contributors to update the README with a new example.

Example:

![image](https://github.com/user-attachments/assets/15c9c8f3-9b7d-49cf-992e-6835991da91d)

Rather than images from a computer it would be nice to have a standard tool that all contributors could use to generate the examples. [Terminalizer](https://www.terminalizer.com/) or equivalent could work but I think I'd prefer the images be static rather than gif - could be convinced otherwise though. Scope of this story would be to recommend a tool, get approval from the maintainers, then implement it for the README.md and Index.md pages. The final step would be adding the instructions for generating the image - including required settings so they look exactly the same - on the CONTRIBUTING.md page.

**Comment by jackneer** [comment]
@kehoecj 
I'd like to give it a try!

**Comment by kehoecj** [comment]
@jackneer go for it!
