### ISSUE TITLE
Cannot exclude type yml from file list

### ISSUE THREAD

**Issue by kehoecj** [Boeing/config-file-validator#205]
`validator --exclude-file-types=yml` raises throws an error that it's an invalid file type

**Comment by gurukiran07** [comment]
I can work on this.

**Comment by gurukiran07** [comment]
PR: #206

**Comment by gurukiran07** [comment]
`validator --exclude-file-types=YAML` also fails. The current search is case-sensitive. Do we want to make it case-insensitive? 

@kehoecj

**Comment by kehoecj** [comment]
> `validator --exclude-file-types=YAML` also fails. The current search is case-sensitive. Do we want to make it case-insensitive?
> 
> @kehoecj

@gurukiran07 Case insensitive would be nice if you can
