### ISSUE TITLE
Display version when running `validator version`

### ISSUE THREAD

**Issue by kehoecj** [Boeing/config-file-validator#24]
## Description

Support displaying the release version when running `validator --version`. This pattern is supported in most golang cli tools

**Comment by gokulav137** [comment]
Hi @kehoecj, Doesn't `validator version` conflict with the current implementation as the argument is supposed to be the path. Should this be implemented as `validator --version` or am I missing something here.

**Comment by kehoecj** [comment]
> Hi @kehoecj, Doesn't `validator version` conflict with the current implementation as the argument is supposed to be the path. Should this be implemented as `validator --version` or am I missing something here.

Good question! I wrote the story like this because I feel like I've seen most go-based CLI's follow golang's convention of using `go version` rather than `validator --version` like in python and other languages. The current argument implementation would definitely need some refactoring to support it. The project is growing enough that it may be time to bring in a CLI library like @ravsii suggested a while back to make things like this easier/more-consistent

**Comment by ravsii** [comment]
My 5 cents on this: Go is pretty much an exception, rather than the rule for using `go help x` instead of `go x --help`. Almost every CLI supports 2nd version with `--help`, but I can't remember anything but go for `go help x` pattern

**Comment by gokulav137** [comment]
Maybe we can implement the version using `--version` first and then have a separate issue to switch to a CLI library like https://github.com/spf13/cobra.

**Comment by kehoecj** [comment]
> Maybe we can implement the version using `--version` first and then have a separate issue to switch to a CLI library like https://github.com/spf13/cobra.

Thanks for feedback ravsii. I would be good with getting `--version` implemented first and then using whatever standard the CLI library that we choose uses. I'll create the future issue to upgrade to cobra (probably wait until Hacktoberfest or until PR's slow down a bit since such a change would require a lot of refactoring).

**Comment by gokulav137** [comment]
I am thinking embedding the version in the LDFlags and then returning that value when --version flag is passed. We can update the release action to add the release tag as the version during the build step.

If this makes sense, I can draft a PR @kehoecj.
