### ISSUE TITLE
Upgrade to go version 1.21

### ISSUE THREAD

**Issue by kehoecj** [Boeing/config-file-validator#36]
Upgrade the config file validator to go version 1.21. As part of the update the following code revisions should be made:

* Replace the [isExtensionIncluded](https://github.com/Boeing/config-file-validator/pull/35/files#diff-a65676dbf68cd041d9bfecd616a578a7fbd7a2f8a85656b073281acca0026af4R120) function with `slice.contains`

Also the following updates need to be made to the repo:

* Update the Dockerfile to use go:1.21 (also go ahead and update Apline Linux version too)
* Update the go.mod to specifu go:1.21
* Update the version of go used by the Github Action runner
* Update the release Github Action runner

**Comment by sandyydk** [comment]
@kehoecj Can I pick this up? Thanks.

**Comment by sandyydk** [comment]
Also @kehoecj did you mean IsExclusionExcluded?

**Comment by sandyydk** [comment]
@kehoecj https://github.com/Boeing/config-file-validator/pull/50

**Comment by sandyydk** [comment]
Can you trigger PR check? I think it's waiting on your approval to run the
check.

**Comment by kehoecj** [comment]
> Also @kehoecj did you mean IsExclusionExcluded?

Yes, sorry I did mean that - good catch!
