### ISSUE TITLE
Add support for ini files

### ISSUE THREAD

**Issue by kehoecj** [Boeing/config-file-validator#4]
## Description

Add support for `.ini` files. INI files are frequently used on the windows platform as well as ansible and other python tools . Use the [go-ini](https://github.com/go-ini/ini) library for the validator.

**Comment by g41797** [comment]
i can take it early June

**Comment by kehoecj** [comment]
@g41797 That'd be great, thanks!

**Comment by g41797** [comment]
[go-ini](https://github.com/go-ini/ini) has set of options for different formats of ini files : [LoadOptions](https://pkg.go.dev/github.com/go-ini/ini#LoadOptions)
Two possibilities:

- set default values for expected ini format 
- add configurator for file type or at least optional map[string]string

Let's discuss

**Comment by kehoecj** [comment]
> [go-ini](https://github.com/go-ini/ini) has set of options for different formats of ini files : [LoadOptions](https://pkg.go.dev/github.com/go-ini/ini#LoadOptions) Two possibilities:
> 
>     * set default values for expected ini format
> 
>     * add configurator for file type or at least optional map[string]string
> 
> 
> Let's discuss

I'd vote for using calling the main [Load function](https://github.com/go-ini/ini/blob/v1.67.0/ini.go#L156) with the default values for the initial implementation.

**Comment by g41797** [comment]
Draft PR #25 was created
Please review

**Comment by g41797** [comment]
i'll try to dive deeper
