### ISSUE TITLE
Add support for multiple search paths

### ISSUE THREAD

**Issue by kehoecj** [Boeing/config-file-validator#45]
## Description

The config-file-validator currently only supports a single search path. Users will probably want the ability to specify several search paths with a single execution and have the results rolled up into a single report.

```
validator /path/to/search/a /path/to/search/b
```

**Comment by gokulav137** [comment]
Hi @kehoecj, I would like to contribute to this feature.

**Comment by kehoecj** [comment]
Assigned to you - thanks!
