### ISSUE TITLE
Add syntax validation support for properties files

### ISSUE THREAD

**Issue by kehoecj** [Boeing/config-file-validator#51]
Add a new properties validator to validate properties files. Golang does not have a build-in properties parser so one from the OSS Community will need to be used - [one option](https://pkg.go.dev/github.com/magiconair/properties). This would be syntax-validation of the properties files only, not semantic validation. Unit tests covering the new properties validator should be included as part of the PR.

**Comment by gokulav137** [comment]
Hi @kehoecj, I would like to contribute to this feature. Will work on drafting a PR.

**Comment by kehoecj** [comment]
> Hi @kehoecj, I would like to contribute to this feature. Will work on drafting a PR.

It's yours! Let us know if you have any questions

**Comment by gokulav137** [comment]
Hi @kehoecj. I have created a PR, could you please review it. Thanks
