### ISSUE TITLE
Add support for HOCON config files

### ISSUE THREAD

**Issue by kehoecj** [Boeing/config-file-validator#64]
Add support for [HOCON](https://docs.spongepowered.org/stable/en/server/getting-started/configuration/hocon.html) validation. This was [requested](https://www.reddit.com/r/golang/comments/175su7h/validate_all_your_config_file_types_with_a_single/k4iz2s3/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) by the community. Looks like there is an available HOCON go parser: https://pkg.go.dev/github.com/gurkankaymak/hocon

**Comment by chriscarnold** [comment]
Could it be that this is referring to [HOCON ?](https://docs.spongepowered.org/stable/en/server/getting-started/configuration/hocon.html) @kehoecj

**Comment by kehoecj** [comment]
> Could it be that this is referring to [HOCON ?](https://docs.spongepowered.org/stable/en/server/getting-started/configuration/hocon.html) @kehoecj 

I think you're right - thanks! I'll update the issue

**Comment by godlixe** [comment]
Hi @kehoecj I'd like to take a shot at this issue if possible!
