### ISSUE TITLE
Automate releases

### ISSUE THREAD

**Issue by kehoecj** [Boeing/config-file-validator#7]
## Description

Automate the current manual release process using Github Actions. We'd like to have linux, windows, and MacOS binaries released automatically when a tag is created. Look into [goreleaser](https://github.com/goreleaser/goreleaser) as a single tool to do all that we want.

**Comment by LeslieLeung** [comment]
Maybe you should have a look at https://github.com/wangyoucao577/go-release-action.

**Comment by kehoecj** [comment]
> Maybe you should have a look at https://github.com/wangyoucao577/go-release-action.

That looks like exactly what I need - thank you!
