### ISSUE TITLE
Add a contributor section on the website

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [Boeing/config-file-validator#70]
- Contributor section above the footer section.
- Hexagon shape.
- Hover effect to grow up.
- Glow and large shape effect with neon light.
- Enlist and fetch them using JS.

**Comment by Avdhesh-Varshney** [comment]
Please assign this issue to me to contribute it under hacktoberfest 2023.

**Comment by kehoecj** [comment]
Great idea! Assigned to you

**Comment by kehoecj** [comment]
@Avdhesh-Varshney Are you still interested in working this?

**Comment by TheAlchemistKE** [comment]
Hey, I am new here. Can I start off with this issue?

**Comment by kehoecj** [comment]
> Hey, I am new here. Can I start off with this issue?

Sure thing!

**Comment by TheAlchemistKE** [comment]
Perfect. Please assign it to me then.

**Comment by vicheanath** [comment]
I saw this issue open a long time 
I recommend this one it should be easy, but I'm not sure it working in HTML render or not


## Contributors

<a href="https://github.com/Boeing/config-file-validator/graphs/contributors">
  <img src="https://contrib.rocks/image?repo=Boeing/config-file-validator" />
</a>

**Comment by kehoecj** [comment]
@TheAlchemistKE Did you still want to work this?
