### ISSUE TITLE
Add go module cache to the Go Pipeline

### ISSUE THREAD

**Issue by kehoecj** [Boeing/config-file-validator#73]
## Description
Github actions has caching capabilities. It would make the builds faster if the modules the config-file-validator depends on were cached for builds and unit tests. The story is to look into ways to implement caching in the current [Go pipeline](https://github.com/Boeing/config-file-validator/blob/main/.github/workflows/go.yml)

**Comment by u5surf** [comment]
@kehoecj  Hi, I would like to work on this issue.

**Comment by kehoecj** [comment]
@u5surf It's yours!
