### ISSUE TITLE
Release config-file-validator as a container

### ISSUE THREAD

**Issue by kehoecj** [Boeing/config-file-validator#8]
## Description
Release the config-file-validator as a container to the [Github Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry). The tag should match the release version. We want to release three versions of the container per release:

1. A full-featured container based on ubuntu
2. A minimalistic container based on alpine
3. A scratch container with the statically-linked config-file-validator

The Github action for creating the containers should run on release.

**Comment by gokulav137** [comment]
Hi @kehoecj, I would like to contribute to this feature.

**Comment by kehoecj** [comment]
> Hi @kehoecj, I would like to contribute to this feature.

Thanks - this will be great to have. Assigned!
