### ISSUE TITLE
Add support for HCL files

### ISSUE THREAD

**Issue by kehoecj** [Boeing/config-file-validator#9]
## Description

Add support for `hcl` configuration files. HCL files are primarily used in Hashicorp tools. There is an official [HCL](https://pkg.go.dev/github.com/hashicorp/hcl/v2) package that can be used for the HCL validator

**Comment by prestonvasquez** [comment]
@kehoecj I'll pick this up!

**Comment by kehoecj** [comment]
> @kehoecj I'll pick this up!

Thanks @prestonvasquez - it's yours!
